[project]
name = "weather-agent"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.0.1",
    "langchain-openai>=1.0.1",
    "langgraph>=1.0.1",
    "langgraph-cli",
    "python-dotenv>=1.1.1",
]

[tool.setuptools]
packages = ["weather_agent"]
